#ifndef FCU_COMMANDS
#define FCU_COMMANDS


#define COMMAND_FD_TOGGLE             "FD_TOGGLE"
#define COMMAND_ILS_TOGGLE            "ILS_TOGGLE"

#define COMMAND_LOC_TOGGLE            "LOC_TOGGLE"

#define COMMAND_AP_1_TOGGLE           "AP1_TOGGLE"
#define COMMAND_AP_2_TOGGLE           "AP2_TOGGLE"
#define COMMAND_A_THR_TOGGLE          "A_THR_TOGGLE"

#define COMMAND_EXPED_TOGGLE          "EXPED_TOGGLE"
#define COMMAND_APPR_TOGGLE           "APPR_TOGGLE"

#define COMMAND_BARO_SET_STD          "BARO_SET_STD"
#define COMMAND_BARO_INCREMENT        "BARO_INCREMENT"
#define COMMAND_BARO_DECREMENT        "BARO_DECREMENT"

#define COMMAND_SPD_SELECT            "SPD_SELECT"
#define COMMAND_SPD_MANAGED           "SPD_MANAGED"
#define COMMAND_SPD_INCREMENT         "SPD_INCREMENT"
#define COMMAND_SPD_DECREMENT         "SPD_DECREMENT"

#define COMMAND_HDG_SELECT            "HDG_SELECT"
#define COMMAND_HDG_MANAGED           "HDG_MANAGED"
#define COMMAND_HDG_INCREMENT         "HDG_INCREMENT"
#define COMMAND_HDG_DECREMENT         "HDG_DECREMENT"

#define COMMAND_ALT_SELECT            "ALT_SELECT"
#define COMMAND_ALT_MANAGED           "ALT_MANAGED"
#define COMMAND_ALT_INCREMENT         "ALT_INCREMENT"
#define COMMAND_ALT_DECREMENT         "ALT_DECREMENT"


#define COMMAND_LEVEL_OFF             "LEVEL_OFF"
#define COMMAND_VS_INCREMENT          "VS_INCREMENT"
#define COMMAND_VS_DECREMENT          "VS_DECREMENT"

#endif
